In [54]:
import pandas as pd

# Load CIRIGHTS data
df = pd.read_excel("cirights_v3.xlsx")

# Basic check
df.tail()

,country,year,ciri,cow,polity,unctry,unreg,unsubreg,Overall Human Rights Score,Physical Integrity Rights Index,...,Women's Social Rights Laws,Union Laws,Collective Bargaining Laws,Legal Limitations on Work Hours,Forced Labor Laws,Child Labor Laws,Minimum Wage Laws,Occupational Safety and Health Laws,Human Trafficking Laws,Fair Trial Laws
7926,South Sudan,2018,700,626.0,525.0,728.0,2.0,15.0,NaN,0.0,...,2.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0
7927,South Sudan,2019,700,626.0,525.0,728.0,2.0,15.0,20.000000,0.0,...,0.0,1.0,1.0,0.0,1.0,2.0,0.0,1.0,1.0,0.0
7928,South Sudan,2020,700,626.0,525.0,728.0,2.0,15.0,14.000000,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
7929,South Sudan,2021,700,626.0,525.0,728.0,2.0,15.0,12.666667,1.0,...,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,NaN,0.0
7930,South Sudan,2022,700,626.0,525.0,728.0,2.0,15.0,8.666667,1.0,...,0.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,NaN,1.0

In [55]:
# Shape: rows × columns
df.shape

# Column names
df.columns

Index(['country', 'year', 'ciri', 'cow', 'polity', 'unctry', 'unreg',
       'unsubreg', 'Overall Human Rights Score',
       'Physical Integrity Rights Index', 'Repression Index',
       'Civil and Political Rights Index', 'Worker Rights Practice Index',
       'Worker Rights Law Index', 'Brutality-based Atrocity',
       'Atrocity Intensity', 'Disappearances', 'Extrajudicial Killings',
       'Political Imprisonment', 'Torture',
       'Freedom of Assembly and Association', 'Freedom of Foreign Movement',
       'Freedom of Domestic Movement', 'Freedom of Speech',
       'Electoral Self-determination', 'Religious Freedom', 'Union Rights',
       'Collective Bargaining', 'Limitations on Work Hours', 'Forced Labor',
       'Child Labor', 'Minimum Wage', 'Occupational Safety and Health',
       'Human Trafficking', 'Judicial Independence', 'Women's Economic Rights',
       'Women's Political Rights', 'Women's Social Rights',
       'Human Rights NGO Freedom', 'Right to a Fair Trial',
       'Women's Social Rights Laws', 'Union Laws',
       'Collective Bargaining Laws', 'Legal Limitations on Work Hours',
       'Forced Labor Laws', 'Child Labor Laws', 'Minimum Wage Laws',
       'Occupational Safety and Health Laws', 'Human Trafficking Laws',
       'Fair Trial Laws'],
      dtype='object')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7931 entries, 0 to 7930
Data columns (total 50 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              7931 non-null   object
 1   year                                 7931 non-null   int64
 2   ciri                                 7931 non-null   int64
 3   cow                                  7919 non-null   float64
 4   polity                               7919 non-null   float64
 5   unctry                               7856 non-null   float64
 6   unreg                                7919 non-null   float64
 7   unsubreg                             7919 non-null   float64
 8   Overall Human Rights Score           3116 non-null   float64
 9   Physical Integrity Rights Index      7089 non-null   float64
 10  Repression Index                     6629 non-null   float64
 11  Civil and Political Rights Index     7051 non-null   float64
 12  Worker Rights Practice Index         5543 non-null   float64
 13  Worker Rights Law Index              5541 non-null   float64
 14  Brutality-based Atrocity             7089 non-null   float64
 15  Atrocity Intensity                   1207 non-null   float64
 16  Disappearances                       7110 non-null   float64
 17  Extrajudicial Killings               7107 non-null   float64
 18  Political Imprisonment               7115 non-null   float64
 19  Torture                              7113 non-null   float64
 20  Freedom of Assembly and Association  7063 non-null   float64
 21  Freedom of Foreign Movement          7638 non-null   float64
 22  Freedom of Domestic Movement         7635 non-null   float64
 23  Freedom of Speech                    7074 non-null   float64
 24  Electoral Self-determination         7074 non-null   float64
 25  Religious Freedom                    7626 non-null   float64
 26  Union Rights                         5555 non-null   float64
 27  Collective Bargaining                5557 non-null   float64
 28  Limitations on Work Hours            5556 non-null   float64
 29  Forced Labor                         5553 non-null   float64
 30  Child Labor                          5552 non-null   float64
 31  Minimum Wage                         5558 non-null   float64
 32  Occupational Safety and Health       5555 non-null   float64
 33  Human Trafficking                    3997 non-null   float64
 34  Judicial Independence                7583 non-null   float64
 35  Women's Economic Rights              7002 non-null   float64
 36  Women's Political Rights             7050 non-null   float64
 37  Women's Social Rights                3446 non-null   float64
 38  Human Rights NGO Freedom             4431 non-null   float64
 39  Right to a Fair Trial                7268 non-null   float64
 40  Women's Social Rights Laws           3449 non-null   float64
 41  Union Laws                           5553 non-null   float64
 42  Collective Bargaining Laws           5555 non-null   float64
 43  Legal Limitations on Work Hours      5552 non-null   float64
 44  Forced Labor Laws                    5552 non-null   float64
 45  Child Labor Laws                     5550 non-null   float64
 46  Minimum Wage Laws                    5556 non-null   float64
 47  Occupational Safety and Health Laws  5557 non-null   float64
 48  Human Trafficking Laws               4006 non-null   float64
 49  Fair Trial Laws                      7269 non-null   float64
dtypes: float64(47), int64(2), object(1)
memory usage: 3.0+ MB

In [57]:
df.describe()

,year,ciri,cow,polity,unctry,unreg,unsubreg,Overall Human Rights Score,Physical Integrity Rights Index,Repression Index,...,Women's Social Rights Laws,Union Laws,Collective Bargaining Laws,Legal Limitations on Work Hours,Forced Labor Laws,Child Labor Laws,Minimum Wage Laws,Occupational Safety and Health Laws,Human Trafficking Laws,Fair Trial Laws
count,7931.000000,7931.000000,7919.000000,7919.000000,7856.000000,7919.000000,7919.000000,3116.000000,7089.000000,6629.000000,...,3449.000000,5553.000000,5555.000000,5552.000000,5552.000000,5550.000000,5556.000000,5557.000000,4006.000000,7269.000000
mean,2001.935948,394.245366,468.154060,468.035484,431.527495,141.755777,56.461296,53.126230,5.014388,9.339870,...,2.128443,1.341977,1.048785,1.233970,1.654179,1.453694,1.088193,1.438186,1.225162,1.998212
std,12.030979,170.771890,264.935745,264.866691,254.101728,142.913657,54.526439,23.296641,2.364336,4.666411,...,1.006086,0.638519,0.647671,0.591337,0.597542,0.627880,0.624548,0.623804,0.743327,0.961489
min,1981.000000,101.000000,2.000000,2.000000,4.000000,2.000000,5.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1992.000000,248.000000,255.000000,260.000000,208.000000,2.000000,14.000000,36.000000,3.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,2002.000000,395.000000,451.000000,451.000000,428.000000,142.000000,35.000000,50.666668,5.000000,9.000000,...,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000
75%,2012.000000,539.000000,690.000000,690.000000,646.000000,150.000000,62.000000,73.333336,7.000000,13.000000,...,3.000000,2.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,3.000000
max,2022.000000,700.000000,990.000000,990.000000,894.000000,419.000000,155.000000,100.000000,8.000000,17.000000,...,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000

In [58]:
df[df["country"] == "Denmark"].tail()

,country,year,ciri,cow,polity,unctry,unreg,unsubreg,Overall Human Rights Score,Physical Integrity Rights Index,...,Women's Social Rights Laws,Union Laws,Collective Bargaining Laws,Legal Limitations on Work Hours,Forced Labor Laws,Child Labor Laws,Minimum Wage Laws,Occupational Safety and Health Laws,Human Trafficking Laws,Fair Trial Laws
1966,Denmark,2018,245,390.0,390.0,208.0,150.0,154.0,94.000000,8.0,...,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0
1967,Denmark,2019,245,390.0,390.0,208.0,150.0,154.0,90.000000,7.0,...,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0
1968,Denmark,2020,245,390.0,390.0,208.0,150.0,154.0,84.000000,7.0,...,3.0,2.0,2.0,2.0,2.0,1.0,0.0,2.0,2.0,3.0
1969,Denmark,2021,245,390.0,390.0,208.0,150.0,154.0,92.000000,7.0,...,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,3.0
1970,Denmark,2022,245,390.0,390.0,208.0,150.0,154.0,92.666664,7.0,...,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0

In [59]:
df["year"].unique()

array([1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

## Making our new dataset

In [60]:
df_clean = df[[
    "country",
    "year",
    "Physical Integrity Rights Index",
    "Freedom of Speech",
    "Judicial Independence",
    "Women's Economic Rights"
]].copy()

df_clean = df_clean.rename(columns={
    "Physical Integrity Rights Index": "physical_integrity",
    "Freedom of Speech": "speech",
    "Judicial Independence": "judicial_independence",
    "Women's Economic Rights": "women_econ"
})

In [61]:
df_clean = df_clean[df_clean["year"] == 2018].copy()
df_clean = df_clean.dropna()

In [62]:
df_clean.describe()

,year,physical_integrity,speech,judicial_independence,women_econ
count,190.0,190.000000,190.000000,190.000000,190.000000
mean,2018.0,5.494737,1.068421,0.942105,0.989474
std,0.0,2.498142,0.727795,0.849410,0.634039
min,2018.0,0.000000,0.000000,0.000000,0.000000
25%,2018.0,4.000000,1.000000,0.000000,1.000000
50%,2018.0,6.000000,1.000000,1.000000,1.000000
75%,2018.0,8.000000,2.000000,2.000000,1.000000
max,2018.0,8.000000,2.000000,2.000000,3.000000

## Merging with fake data

In [63]:

treaty_data = pd.DataFrame({
    "country": [
        "Germany", "United States", "China", "India", "Saudi Arabia",
        "France", "Brazil", "Denmark", "Turkey", "Egypt"
    ],
    "iccpr": [1,1,0,1,1,1,1,1,1,1],
    "cat":   [1,1,0,1,1,1,1,1,1,1],
    "cedaw": [1,0,1,1,1,1,1,1,1,1],
    "reservations_total": [0,5,3,2,7,0,1,0,4,6]
})

treaty_data

         country  iccpr  cat  cedaw  reservations_total
0        Germany      1    1      1                   0
1  United States      1    1      0                   5
2          China      0    0      1                   3
3          India      1    1      1                   2
4   Saudi Arabia      1    1      1                   7
5         France      1    1      1                   0
6         Brazil      1    1      1                   1
7        Denmark      1    1      1                   0
8         Turkey      1    1      1                   4
9          Egypt      1    1      1                   6

In [64]:
set(df_clean["country"]) - set(treaty_data["country"])

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia Herzegovenia',
 'Botswana',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burma (Myanmar)',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'Colombia',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Côte d’Ivoire',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor (Timor-Leste)',
 'Ecuador',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'Gabon',
 'Gambia, The',
 'Georgia',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kyrgyz Republic',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Federated States of',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovak Republic/ Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [65]:
merged = df_clean.merge(treaty_data, on="country", how="inner")

merged.head()

,country,year,physical_integrity,speech,judicial_independence,women_econ,iccpr,cat,cedaw,reservations_total
0,Brazil,2018,5.0,2.0,1.0,1.0,1,1,1,1
1,China,2018,0.0,0.0,0.0,1.0,0,0,1,3
2,Denmark,2018,8.0,2.0,2.0,1.0,1,1,1,0
3,Egypt,2018,0.0,0.0,0.0,1.0,1,1,1,6
4,France,2018,7.0,2.0,2.0,1.0,1,1,1,0

In [66]:
merged.shape

(9, 10)

### ICPR

In [67]:
!pip install pdfplumber pandas

import pdfplumber
import pandas as pd
import re

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.6.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)

In [68]:
import pdfplumber
import pandas as pd
import re
from collections import defaultdict

# --------------------------------------------------
# 1. Load CIRIGHTS and build whitelist
# --------------------------------------------------
cirights = pd.read_excel("cirights_v3.xlsx")

valid_countries = set(
    cirights["country"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

# Add aliases only if the canonical CIRIGHTS name exists
candidate_aliases = {
    "USA": "United States",
    "UK": "United Kingdom",
    "Viet Nam": "Vietnam",
    "Republic of Korea": "South Korea",
    "Lao PDR": "Laos",
    "Russian Federation": "Russia",
    "Syrian Arab Republic": "Syria",
    "Türkiye": "Turkey",
}

aliases = {
    k: v for k, v in candidate_aliases.items()
    if v in valid_countries
}

# Search names used in the ICCPR PDF -> canonical CIRIGHTS names
search_names = {}

for c in valid_countries:
    search_names[c] = c

for pdf_name, canonical_name in aliases.items():
    search_names[pdf_name] = canonical_name

# Sort by length so "Trinidad and Tobago" is matched before shorter fragments
search_items = sorted(search_names.items(), key=lambda x: len(x[0]), reverse=True)

# --------------------------------------------------
# 2. Read ICCPR PDF text (pages 1-2 only)
# --------------------------------------------------
pdf_path = "List_of_ICCPR_reservations.pdf"

raw_text = ""
with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages[:2]:
        t = page.extract_text()
        if t:
            raw_text += t + "\n"

start_marker = "1. Reservations / declarations made by State parties per ICCPR Article"
end_marker = "2. Reservations / declarations made on ICCPR per State parties"

start_idx = raw_text.find(start_marker)
end_idx = raw_text.find(end_marker)

section1 = raw_text[start_idx:end_idx]

# Light cleanup
section1 = section1.replace("\u00ad", " ")
section1 = re.sub(r"\s+", " ", section1).strip()

# --------------------------------------------------
# 3. Split into article blocks
# --------------------------------------------------
article_blocks = re.split(r'(?=Article\s+\d+)', section1)

country_to_articles_all = defaultdict(set)
country_to_articles_res_only = defaultdict(set)

for block in article_blocks:
    block = block.strip()
    if not block.startswith("Article"):
        continue

    m = re.match(r"Article\s+(\d+)", block)
    if not m:
        continue

    article_num = int(m.group(1))

    # remove the leading "Article X"
    rest = re.sub(r"^Article\s+\d+\s*", "", block).strip()

    # remove trailing count column if present
    rest = re.sub(r"\s+\d+\s*$", "", rest).strip()

    # Now, instead of trusting split entries, search for known countries directly
    for search_name, canonical_name in search_items:
        pattern = rf'(?<![A-Za-z]){re.escape(search_name)}(?![A-Za-z])'

        for match in re.finditer(pattern, rest):
            country_to_articles_all[canonical_name].add(article_num)

            # Look from this match to the next semicolon; that is the local entry
            next_sep = rest.find(";", match.start())
            if next_sep == -1:
                segment = rest[match.start():]
            else:
                segment = rest[match.start():next_sep]

            # reservations only = exclude entries explicitly marked as declaration
            if "declaration" not in segment.lower():
                country_to_articles_res_only[canonical_name].add(article_num)

# --------------------------------------------------
# 4. Build final dataframe
# --------------------------------------------------
all_countries_found = sorted(set(country_to_articles_all) | set(country_to_articles_res_only))

iccpr_df = pd.DataFrame({"country": all_countries_found})

iccpr_df["iccpr_qualifications"] = iccpr_df["country"].map(
    lambda c: len(country_to_articles_all.get(c, set()))
)

iccpr_df["iccpr_res_only"] = iccpr_df["country"].map(
    lambda c: len(country_to_articles_res_only.get(c, set()))
)

iccpr_df = iccpr_df.sort_values("country").reset_index(drop=True)

print("Rows:", iccpr_df.shape[0])
display(iccpr_df.head(20))

display(
    iccpr_df[
        iccpr_df["country"].isin([
            "United States", "United Kingdom", "India", "Algeria",
            "Turkey", "Denmark", "France", "Germany", "Trinidad and Tobago"
        ])
    ].sort_values("country")
)

Rows: 53

        country  iccpr_qualifications  iccpr_res_only
0   Afghanistan                     1               1
1       Algeria                     1               1
2     Argentina                     1               1
3     Australia                     3               3
4       Austria                     8               8
5       Bahamas                     1               1
6       Bahrain                     5               5
7    Bangladesh                     3               0
8      Barbados                     1               1
9       Belgium                     6               5
10       Belize                     2               2
11     Botswana                     2               2
12     Bulgaria                     1               1
13      Denmark                     3               3
14      Finland                     3               3
15       France                     8               3
16      Germany                     5               5
17       Guinea                     1               1
18       Guyana                     1               1
19      Hungary                     1               1

                country  iccpr_qualifications  iccpr_res_only
1               Algeria                     1               1
13              Denmark                     3               3
15               France                     8               3
16              Germany                     5               5
21                India                     6               5
47  Trinidad and Tobago                     6               6
48               Turkey                     1               1
50       United Kingdom                     9               9

In [69]:
def inspect_country(country_name):
    print(f"\n=== {country_name} ===\n")

    for block in article_blocks:
        if country_name.lower() in block.lower():
            print(block[:500])
            print("\n---\n")


inspect_country("France")
inspect_country("United States")
inspect_country("India")
inspect_country("Denmark")

=== France ===

Article 4 France (para.1); Trinidad and Tobago (para.2) 2

---

Article 8 Samoa (para.3) 1 Austria; Bahrain (para.5); France; India (declaration); Mexico (declaration on para.5); USA

---

Article 13 France (declaration); India; Malta; Monaco (declaration); UK 5 Australia; Austria; Bahamas (para.6); Bahrain (para.7); Bangladesh (para.3 d and declaration); Barbados (para.3 d); Belgium; Belize (paras.3 d and 6); Denmark (paras.1, 5 and 7); Finland (para.7); France; Gambia (para.3 d); Germany (paras.3 d and 5); Guyana

---

Article 18 Bahrain; Lao PDR (declaration); Maldives; Mauritania; Mexico (declaration) 5 Austria; Belgium; France (declaration); Germany; India (para.3); Italy (para.3); Luxembourg

---

Article 19 10 (para.2); Malta; Monaco (declaration); Netherlands (para.2) Australia; Belgium (declaration on para.1); Denmark (para.1); Finland (para.1); France (declaration on para.1); Iceland (para.1); Ireland (para.1); Luxembourg (para.1); Malta;

---

Article 20 17 Netherlands (para.1); New Zealand; Norway; Sweden (para.1); Switzerland; Thailand (declaration on para.1); UK; USA Austria; Belgium; France (declaration); Germany; India; Monaco (declaration); Trinidad and

---

Article 22 Algeria; Austria; Belgium; France (declaration); Germany; India; Japan (declaration on 12 1 Excluding the declarations recognising the competence of the Human Rights Committee under ICCPR article 41 on inter-State communications 2 Based on the information provided in the Chapter IV.3 and IV.4 of the United Nations Treaty Collections: https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-4&chapter=4&clang=_en 3 Excluding reservations and declarations made in general, wi

---

Article 27 France (declaration); Turkey 2 Afghanistan (paras.1 and 3); Bulgaria (paras.1 and 3); Guinea (para.1); Hungary (paras.1 and

---


=== United States ===


=== India ===

1. Reservations / declarations made by State parties per ICCPR Article3 No. of State parties having Articles State parties having reservations / declarations reservation / declaration Algeria; India (declaration); Indonesia (declaration); Lao PDR (declaration); Thailand

---

Article 8 Samoa (para.3) 1 Austria; Bahrain (para.5); France; India (declaration); Mexico (declaration on para.5); USA

---

Article 11 Bangladesh (declaration); Congo 2 Austria (para.4); Belize (para.2); Botswana (para.3); India; Netherlands (paras.1, 2 and 4);

---

Article 13 France (declaration); India; Malta; Monaco (declaration); UK 5 Australia; Austria; Bahamas (para.6); Bahrain (para.7); Bangladesh (para.3 d and declaration); Barbados (para.3 d); Belgium; Belize (paras.3 d and 6); Denmark (paras.1, 5 and 7); Finland (para.7); France; Gambia (para.3 d); Germany (paras.3 d and 5); Guyana

---

Article 18 Bahrain; Lao PDR (declaration); Maldives; Mauritania; Mexico (declaration) 5 Austria; Belgium; France (declaration); Germany; India (para.3); Italy (para.3); Luxembourg

---

Article 20 17 Netherlands (para.1); New Zealand; Norway; Sweden (para.1); Switzerland; Thailand (declaration on para.1); UK; USA Austria; Belgium; France (declaration); Germany; India; Monaco (declaration); Trinidad and

---

Article 22 Algeria; Austria; Belgium; France (declaration); Germany; India; Japan (declaration on 12 1 Excluding the declarations recognising the competence of the Human Rights Committee under ICCPR article 41 on inter-State communications 2 Based on the information provided in the Chapter IV.3 and IV.4 of the United Nations Treaty Collections: https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-4&chapter=4&clang=_en 3 Excluding reservations and declarations made in general, wi

---


=== Denmark ===

Article 9 6 (declaration on para.5) Australia; Austria (para.3); Bangladesh (declaration); Belgium (paras.2 a and 3); Denmark (para.3); Finland (paras.2b and 3); Iceland (paras.2 b and 3); Ireland (para.2); Luxembourg

---

Article 13 France (declaration); India; Malta; Monaco (declaration); UK 5 Australia; Austria; Bahamas (para.6); Bahrain (para.7); Bangladesh (para.3 d and declaration); Barbados (para.3 d); Belgium; Belize (paras.3 d and 6); Denmark (paras.1, 5 and 7); Finland (para.7); France; Gambia (para.3 d); Germany (paras.3 d and 5); Guyana

---

Article 19 10 (para.2); Malta; Monaco (declaration); Netherlands (para.2) Australia; Belgium (declaration on para.1); Denmark (para.1); Finland (para.1); France (declaration on para.1); Iceland (para.1); Ireland (para.1); Luxembourg (para.1); Malta;

---

In [72]:
iccpr_df.sort_values("iccpr_reservations", ascending=False).head(10)

                country  iccpr_reservations
50       United Kingdom                   9
4               Austria                   8
47  Trinidad and Tobago                   6
9               Belgium                   5
16              Germany                   5
36          Netherlands                   5
21                India                   5
6               Bahrain                   5
44          Switzerland                   4
31                Malta                   4

In [73]:
iccpr_df.to_csv("iccpr_clean.csv", index=False)

## CEDAW

In [76]:
import pandas as pd

cedaw = pd.read_excel("CEDAW_ROCS_Dataset.xlsx")
cirights = pd.read_excel("cirights_v3.xlsx")

In [77]:
cow_map = (
    cirights[["cow", "country"]]
    .dropna()
    .drop_duplicates()
    .copy()
)

cow_map["cow"] = cow_map["cow"].astype(int)

cedaw["ccode"] = cedaw["ccode"].astype(int)

cedaw = cedaw.merge(
    cow_map,
    left_on="ccode",
    right_on="cow",
    how="left"
)

In [78]:
article_cols = [col for col in cedaw.columns if col.startswith("art")]

cedaw[article_cols] = cedaw[article_cols].fillna(0)

cedaw["cedaw_reservations"] = cedaw[article_cols].sum(axis=1)

In [79]:
cedaw = cedaw.sort_values(["country", "year"]).copy()

cedaw["cedaw"] = (
    cedaw.groupby("country")["cedawrat"]
    .cummax()
)

In [80]:
cedaw_df = cedaw[[
    "country",
    "year",
    "cedaw",
    "cedaw_reservations"
]].copy()

In [81]:
cedaw_df["cedaw_reservations"] = (
    cedaw_df["cedaw_reservations"] * cedaw_df["cedaw"]
)

In [82]:
cedaw_df.sort_values("cedaw_reservations", ascending=False).head(15)

             country  year  cedaw  cedaw_reservations
1555  United Kingdom  2002    1.0                 9.0
1554  United Kingdom  2001    1.0                 9.0
1553  United Kingdom  2000    1.0                 9.0
1552  United Kingdom  1999    1.0                 9.0
1551  United Kingdom  1998    1.0                 9.0
1550  United Kingdom  1997    1.0                 9.0
1549  United Kingdom  1996    1.0                 9.0
1548  United Kingdom  1995    1.0                 9.0
1575  United Kingdom  2022    1.0                 9.0
1546  United Kingdom  1993    1.0                 9.0
1545  United Kingdom  1992    1.0                 9.0
1544  United Kingdom  1991    1.0                 9.0
1543  United Kingdom  1990    1.0                 9.0
1542  United Kingdom  1989    1.0                 9.0
1541  United Kingdom  1988    1.0                 9.0

## CAT

In [84]:
import pandas as pd

cat = pd.read_excel("cat_data.xlsx")

print(cat.shape)
print(cat.columns.tolist())
cat.head()

(478, 5)
['Table 1', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

,Table 1,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,Participant,Action,Date of Notification/Deposit,Date of Effect
2,NaN,Afghanistan,Withdrawal of reservation,17/04/2018,NaN
3,NaN,Afghanistan,Signature,04/02/1985,NaN
4,NaN,Afghanistan,Ratification,01/04/1987,26/06/1987

In [85]:
import pandas as pd

cat = pd.read_excel("cat_data.xlsx")
cat.columns = ["drop", "country", "action", "date", "effective_date"]
cat = cat.drop(columns=["drop"]).dropna(subset=["country"])
cat["action"] = cat["action"].astype(str).str.lower()
cat["date"] = pd.to_datetime(cat["date"], dayfirst=True, errors="coerce")
cat["year"] = cat["date"].dt.year

cat_year_df = (
    cat[cat["action"].str.contains("ratification", na=False)]
    .groupby("country")["year"].min()
    .reset_index()
    .rename(columns={"year": "cat_year"})
)

cat_res_df = (
    cat[
        cat["action"].str.contains("reservation", na=False)
        & ~cat["action"].str.contains("withdrawal", na=False)
    ]
    .groupby("country")
    .size()
    .reset_index(name="cat_reservations")
)

cat_df = cat_year_df.merge(cat_res_df, on="country", how="left")
cat_df["cat_reservations"] = cat_df["cat_reservations"].fillna(0)

cat_df.head()

/tmp/ipykernel_5551/1581813929.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cat["date"] = pd.to_datetime(cat["date"], dayfirst=True, errors="coerce")

       country  cat_year  cat_reservations
0  Afghanistan    1987.0               0.0
1      Algeria    1989.0               0.0
2      Andorra    2006.0               0.0
3       Angola    2019.0               0.0
4    Argentina    1986.0               0.0

In [86]:
cat_df["cat_reservations"].value_counts().sort_index()

cat_reservations
0.0    82
Name: count, dtype: int64

In [87]:
cat_df.sort_values("cat_reservations", ascending=False).head(20)

                                   country  cat_year  cat_reservations
0                              Afghanistan    1987.0               0.0
1                                  Algeria    1989.0               0.0
2                                  Andorra    2006.0               0.0
3                                   Angola    2019.0               0.0
4                                Argentina    1986.0               0.0
5                                Australia    1989.0               0.0
6                                  Austria    1987.0               0.0
7                                  Bahamas    2018.0               0.0
8                                  Belgium    1999.0               0.0
9                                  Bolivia    1999.0               0.0
10                                Botswana    2000.0               0.0
11                                  Brazil    1989.0               0.0
12                                Bulgaria    1986.0               0.0
13  Byelorussian Soviet Socialist Republic    1987.0               0.0
14                                  Canada    1987.0               0.0
15                                   Chile    1988.0               0.0
16                                   China    1988.0               0.0
17                                Colombia    1987.0               0.0
18                                 Comoros    2017.0               0.0
19                              Costa Rica    1993.0               0.0

In [88]:
import pandas as pd
import re

# Paste the CAT country-text exactly here
cat_text = """
Afghanistan 14

Austria 15
Declaration:

       “...
       2. Austria regards article 15 as the legal basis for the inadmissibility provided for therein of the use of statements which are established to have been made as a result of torture.”

Bahamas (The)
Reservations:

       “The Government of the Commonwealth of The Bahamas does not recognize the competence of the Committee against Torture as provided for in Article 20 of the UNCAT.
       The Government of the Commonwealth of The Bahamas does not consider itself bound by paragraph 1 of Article 30 of the Convention.
       The Government of the Commonwealth of The Bahamas reserves the right to award compensation to torture victims referred to in Article 14 of the Convention Against Torture only at the discretion of the Supreme or Appellate Courts, or the Attorney-General of the Commonwealth of The Bahamas.”

Bahrain 16
Reservations

       ...
       2. The State of Bahrain does not consider itself bound by paragraph 1 of article 30 of the Convention.

Bangladesh 17, 18
Declaration:

       ...

Belarus 19

Botswana
Reservation made upon signature and confirmed upon ratification:

       “The Government of the Republic of Botswana considers itself bound by Article 1 of the Convention to the extent that ‘torture’ means the torture and inhuman or degrading punishment or other treatment prohibited by Section 7 of the Constitution of the Republic of Botswana.”

Brunei Darussalam
Declaration made upon signature

       “The Government of Brunei Darussalam reserves the right to formulate and communicate, upon ratification, such reservations, interpretative understandings, and/or declarations which it might consider necessary.”

Bulgaria 20

Chile 21
Upon signature:

       ...
       2. The Government of Chile does not consider itself bound by the provisions of article 30, paragraph 1, of the Convention.
       3. The Government of Chile reserve the right to formulate, upon ratifying the Convention, any declarations or reservations it may deem necessary in the light of its domestic law.
Upon ratification:

       The Government of Chile declares that in its relations with American States that are Parties to the Inter-American Convention to Prevent and Punish Torture, it will apply that Convention in cases where its provisions are incompatible with those of the present Convention.
       ...

China
Reservations made upon signature and confirmed upon ratification:

       "(1) The Chinese Government does not recognize the competence of the Committee against Torture as provided for in article 20 of the Convention.
       "(2) The Chinese Government does not consider itself bound by paragraph l of article 30 of the Convention."

Cuba
Declarations:

       The Government of the Republic of Cuba deplores the fact that even after the adoption of General Assembly resolution 1514 (XV) containing the Declaration on the granting of independence to colonial countries and peoples, a provision such as paragraph 1 of article 2 was included in the Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment.
       The Government of the Republic declares, in accordance with article 28 of the Convention, that the provisions of paragraphs 1, 2 and 3 of article 20 of the Convention will have to be invoked in strict compliance with the principle of the sovereignty of States and implemented with the prior consent of the States Parties.
       In connection with the provisions of article 30 of the Convention, the Government of the Republic of Cuba is of the view that any dispute between Parties should be settled by negotiation through the diplomatic channel.

Czech Republic 7

Dominica
Reservations:

       “The Government of the Commonwealth of Dominica does not recognize the competence of the Committee against Torture as provided for in Article 20 of the Convention.
       The Government of the Commonwealth of Dominica does not consider itself bound by paragraph 1 of Article 30 of the Convention.”

Ecuador
Reservation:

       Ecuador declares that, in accordance with the provisions of article 42 of its Political Constitution, it will not permit extradition of its nationals.

Equatorial Guinea
Declaration and reservation:

       First - The Government of Equatorial Guinea hereby declares that, pursuant to article 28 of this Convention, it does not recognize the competence of the Committee provided for in article 20 of the Convention.
       Second - With reference to the provisions of article 30, the Government of Equatorial Guinea does not consider itself bound by paragraph 1 thereof.

Eritrea
Reservations:

       “In accordance with Article 28 of the Convention, Eritrea declares that it does not recognize the competence of the Committee provided for it in article 20.
       The State of Eritrea does not consider itself bound by paragraph 1 of Article 30 which stipulates that all disputes concerning the interpretation or application of the Convention shall be referred to the International Court of Justice by one of the parties.”

Fiji 22, 23
Reservations

       “...
       The Government of the Republic of Fiji recognizes the article 14 of the Convention only to the extent that the right to award compensation to victims of an act of torture shall be subject to the determination of a Court of law.
       The Government of the Republic of Fiji does not recognize the competence of the Committee against Torture as provided for in article(s) 20, 21 and 22 of the Convention and therefore shall not be bound by these provisions.
       The Government of the Republic of Fiji does not recognize paragraph 1 of article 30 of the Convention and therefore shall not be bound by this provision.”

France
Reservation:

       The Government of France declares in accordance with article 30, paragraph 2, of the Convention, that it shall not be bound by the provisions of paragraph 1 of [article 30].

Germany 3
Upon signature:

       The Government of the Federal Republic of Germany reserves the right to communicate, upon ratification, such reservations or declarations of interpretation as are deemed necessary especially with respect to the applicability of article 3.
Upon ratification:

       Article 3
       This provision prohibits the transfer of a person directly to a State where this person is exposed to a concrete danger of being subjected to torture.  In the opinion of the Federal Republic of Germany, article 3 as well as the other provisions of the Convention exclusively establish State obligations that are met by the Federal Republic of Germany in conformity with the provisions of its domestic law which is in accordance with the Convention.

Ghana
Declaration:

       “[The Government of Ghana declares] in accordance with Article 30 (2) of the said Convention that the submission under Article 30 (1) to arbitration or the International Court of Justice of disputes between State Parties relating to the interpretation or application of the said Convention shall be by the consent of ALL the Parties concerned and not by one or more of the Parties concerned.”

Guatemala 24

Guinea-Bissau
Declaration:

       1. Recognize the competence of the Committee Against Torture to receive and consider communications in which a Party claims that another Party is not fulfilling its obligations under this Convention, and
       2. Also declare that we recognize the Committee's competence to receive and consider communications from individuals or groups of individuals within our jurisdiction claiming to be victims of a violation of any of the rights contained in this Convention.

Holy See
Declaration:

       The Holy See considers the Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment a valid and suitable instrument for fighting against acts that constitute a serious offence against the dignity of the human person. In recent times the Catholic Church has consistently pronounced itself in favour of unconditional respect for life itself and unequivocally condemned "whatever violates the integrity of the human person, such as mutilation, torments inflicted on body or mind, attempts to coerce the will itself" (Second Vatican Council, Pastoral Constitution Gaudium et spes, 7 December 1965).
       The law of the Church (Code of Canon Law, 1981) and its catechism (Catechism of the Catholic Church, 1987) enumerate and clearly identify forms of behaviour that can harm the bodily or mental integrity of the individual, condemn their perpetrators and call for the abolition of such acts. On 14 January 1978, Pope Paul VI, in his last address to the diplomatic corps, after referring to the torture and mistreatment practised in various countries against individuals, concluded as follows: "How could the Church fail to take up a stern stand ... with regard to torture and to similar acts of violence inflicted on the human person?" Pope John Paul II, for his part, has not failed to affirm that "torture must be called by its proper name" (message for the celebration of the World Day of Peace, 1 January 1980). He has expressed his deep compassion for the victims of torture (World Congress on Pastoral Ministry for Human Rights, Rome, 4 July 1998), and in particular for tortured women (message to the Secretary-General of the United Nations, 1 March 1993). In this spirit the Holy See wishes to lend its moral support and collaboration tothe international community, so as to contribute to the elimination of recourse to torture, which is inadmissible and inhuman.
       The Holy See, in becoming a party to the Convention on behalf of the Vatican City State, undertakes to apply it insofar as it is compatible, in practice, with the peculiar nature of that State.

Hungary 25

Indonesia
Declaration:

       “The Government of the Republic of Indonesia declares that the provisions of paragraphs 1, 2, and 3 of article 20 of the Convention will have to be implemented in strict compliance with the principles of the sovereignty and territorial integrity of States.
Reservation:

       The Government of the Republic of Indonesia does not consider itself bound by the provision of article 30, paragraph 1, and takes the position that disputes relating to the interpretation and application of the Convention which cannot be settled through the channel provided for in paragraph 1 of the said article, may be referred to the International Court of Justice only with the consent of all parties to the disputes.”

Israel
Reservations:

       "1. In accordance with article 28 of the Convention, the State of Israel hereby declares that it does not recognize the competence of the Committee provided for in article 20.
       "2. In accordance with paragraph 2 of article 30, the State of Israel hereby declares that it does not consider itself bound by paragraph 1 of that article."

Kuwait
Reservation:

       "With reservations as to article (20) and the provision of paragraph (1) from article  (30) of the Convention."

Lao People's Democratic Republic 26
Reservations:

       “The Government of the Lao People’s Democratic Republic, pursuant to Article 28 of the Convention, does not recognize the competence of the Committee against Torture under Article 20.
       The Government of the Lao People’s Democratic Republic does not consider itself bound by the provisions of Article 30, paragraph 1, to refer any dispute concerning the interpretation and application of the Convention to the International Court of Justice.”
Declarations:

       “It is the understanding of the Government of the Lao People’s Democratic Republic that the term ‘torture’ in Article 1, paragraph 1, of the Convention means torture as defined in both national law and international law.
       The Government of the Lao People’s Democratic Republic declares that, pursuant to Article 8, paragraph 2 of the Convention it makes extradition conditional on the existence of a treaty. Therefore, it does not consider the Convention as the legal basis for extradition in respect of the offences set forth therein. It further declares that bilateral agreements will be the basis for extradition as between the Lao People’s Democratic Republic and other States Parties in respect of any offences.”

Luxembourg
Interpretative declaration:

Article l

       The Grand Duchy of Luxembourg hereby declares that the only "lawful sanctions" that it recognizes within the meaning of article 1, paragraph 1, of the Convention are those which are accepted by both national law and international law.

Mauritania
Reservations:

       Article 20
       The Mauritanian Government does not recognize the competence granted to the Committee in article 20 of the Convention, which provides as follows:
       1. If the Committee receives reliable information which appears to it to contain well-founded indications that torture is being systematically practiced in the territory of a State Party, the Committee shall invite that State Party to cooperate in the examination of the information and to this end to submit observations with regard to the information concerned.
       2. Taking into account any observations which may have been submitted by the State Party concerned, as well as any other relevant information available to it, the Committee may, if it decides that this is warranted, designate one or more of its members to make a confidential inquiry and to report to the Committee urgently.
       3. If an inquiry is made in accordance with paragraph 2 of this article, the Committee shall seek the cooperation of the State Party concerned. In agreement with that State Party, such an inquiry may include a visit to its territory.
       4. After examining the findings of its member or members submitted in accordance with paragraph 2 of this article, the Committee shall transmit these findings to the State Party concerned together with any comments or suggestions which seem appropriate in view of the situation.
       5. All the proceedings of the Committee referred to in paragraphs 1 to 4 of this article shall be confidential, and at all stages of the proceedings the cooperation of the State Party shall be sought. After such proceedings have been completed with regard to an inquiry made in accordance with paragraph 2, the Committee may, after consultations with the State Party concerned, decide to include a summary account of the results of the proceedings in its annual report made in accordance with article 24.
       Article 30, paragraph 1
       1. Any dispute between two or more States Parties concerning the interpretation orapplication of this Convention which cannot be settled through negotiation shall, at the request of one of them, be submitted to arbitration. If within six months from the date of the request for arbitration the Parties are unable to agree on the organization of the arbitration, any one of those Parties may refer the dispute to the International Court of Justice by request in conformity with the Statute of the Court.
       Pursuant to article 30, paragraph 2, of the Convention, the Government of Mauritania declares that it does not consider itself bound by paragraph 1 of this article, which provides that in the event of a dispute concerning the interpretation or application of the Convention, one of the Parties may refer the dispute to the International Court of Justice by request.

Monaco
Reservation:

       In accordance with paragraph 2 of article 30 of the Convention, the Principality of Monaco declares that it does not consider itself bound by paragraph 1 of that article.

Morocco 27
Reservations made upon signature and confirmed upon ratification:

       .....
       2. In accordance with article 30, paragraph 2, the Government of the Kingdom of Morocco does not consider itself bound by paragraph 1 of the same article.

Netherlands (Kingdom of the)
Interpretative declaration with respect to article 1:

       "It is the understanding of the Government of the Kingdom of the Netherlands that the term "lawful sanctions" in article 1, paragraph 1, must be understood as referring to those sanctions which are lawful not only under national law but also under international law."

New Zealand
Reservation:

       "The Government of New Zealand reserves the right to award compensation to torture victims referred to in article 14 of the Convention Against Torture only at the discretion of the Attorney-General of New Zealand."

Oman
Reservations:

       1. The Sultanate of Oman declares that it does not recognize the competence of the Committee against Torture as set out in article 20 of the Convention.
       2. The Sultanate of Oman declares that it is not bound by the provisions of article 30, paragraph 1, of the Convention.

Pakistan 28
Upon signature

Reservation:

       “The Government of the Islamic Republic of Pakistan reserves its right to attach appropriate reservations, make declarations and state its understanding in respect of various provisions of the Convention at the time of ratification.”
Reservation made upon ratification:

       “Article 8
       ‘The Government of the Islamic Republic of Pakistan declares that pursuant to Article 8, paragraph 2, of the Convention, it does not take this Convention as the legal basis for cooperation on extradition with other States Parties’.
       Article 28
       ‘In accordance with Article 28, paragraph 1, of the Convention, the Government of the Islamic Republic of Pakistan hereby declares that it does not recognize the competence of the Committee provided for in Article 20’.
       Article 30
       ‘The Government of the Islamic Republic of Pakistan does not consider itself bound by Article 30, Paragraph 1 of the Convention’.”

Panama
       The Republic of Panama declares in accordance with article  30, paragraph 2 of the Convention that it does not consider itself bound by the provisions of paragraph 1 of the said article.

Poland
Upon signature:

       Under article 28, the Polish People's Republic does not consider itself bound by article 20 of the Convention.
       Furthermore, the Polish People's Republic does not consider itself bound by article 30, paragraph 1, of the Convention.
19 December 2025


       On 19 December 2025, Poland informed the Secretary-General that it withdraws its reservation to Article 30 paragraph 1 made upon signature.

Qatar 29, 30
Reservations:

       “ … the State of Qatar :
       1) partially withdraws its general reservation, while keeping in effect a limited general reservation within the framework of Articles 1 and 16 of the Convention, and
       2) withdraws its reservation to the mandate of the Committee against Torture as stipulated in Articles 21 and 22 of the Convention.”

Russian Federation 19

Samoa
Reservations:

       “Article 14
       ‘The Government of the Independent State of Samoa reserves the right to award compensation to torture victims or their families and the question of adequate compensation referred to in Article 14, at the discretion of the Courts of Samoa’.
       Article 20
       ‘The Government of the Independent State of Samoa does not recognise the competence of the Committee against Torture as provided for in Article 20 of the Convention’.
       Article 30
        ‘The Government of the Independent State of Samoa does not consider itself bound by paragraph 1 of Article 30 of the Convention’.”

Saudi Arabia
       Reservations:
       The Kingdom of Saudi Arabia does not recognize the jurisdiction of the Committee as provided for in article 20 of this Convention.
       The Kingdom of Saudi Arabia shall not be bound by the provisions of paragraph (1) of article 30 of this Convention.

Slovakia 7

South Africa
Declaration:

       “[The Republic of South Africa declares that] it recognises, for the purposes of article 30 of the Convention, the competence of the International Court of Justice to settle a dispute between two or more State Parties regarding the interpretation or application of the Convention, respectively."

St. Lucia
Reservations made upon accession:

       1. The Government of Saint Lucia does not recognize the competence of the Committee against Torture as provided for in Article 20 of the Convention;
       2. The Government of Saint Lucia does not consider itself bound by paragraph 1 of Article 30 of the Convention.

Sudan
Declaration:

       “… the Government of the Republic of the Sudan, in accordance with article (30) paragraph (2) doesn’t consider itself bound by the provisions of the article (30) paragraph (1) of this Convention.”

Syrian Arab Republic
Declarations:

       In accordance with the provisions of article 28, paragraph 1, of the Convention, the Syrian Arab Republic does not recognize the competence of the Committee against Torture provided for in article 20 thereof;
       The accession of the Syrian Arab Republic to this Convention shall in no way signify recognition of Israel or entail entry into any dealings with Israel in the context of the provisions of this Convention.

Thailand 31
Reservation:

       "The Kingdom of Thailand does not consider itself bound by Article 30, paragraph 1, of the Convention."

Togo
Upon signature:

       The Government of the Togolese Republic reserves the right to formulate, upon ratifying the Convention, any reservations or declarations which it might consider necessary.

Tunisia 32
Upon ratification:

       [The Government of Tunisia] confirms that the reservations made at the time of signature of the Convention on Tunisia's behalf on 26 August 1987 have been completely withdrawn.

Türkiye
Reservation:

       "The Government of Turkey declares in accordance with article 30, paragraph 2, of the Convention, that it does not consider itself bound by the provisions of paragraph 1 of this article."

Tuvalu
Reservation

       “The Government of Tuvalu does not recognize paragraph 1 of article 30 of the Convention and therefore shall not be bound by this provision.”

Ukraine 19

United Arab Emirates
Reservations

       In accordance with paragraph 1 of article 28 of the Convention, the United Arab Emirates declares that it does not recognize the competence of the Committee against Torture referred to in article 20 of the Convention.
       In accordance with paragraph 2 of article 30 of the Convention, the United Arab Emirates does not consider itself bound by paragraph 1 of article 30 relating to arbitration in this Convention.
Declaration

        The United Arab Emirates also confirms that the lawful sanctions applicable under national law, or pain or suffering arising from or associated with or incidental to these lawful sanctions, do not fall under the concept of  “torture” defined in article 1 of this Convention or under the concept of cruel, inhuman or degrading treatment or punishment mentioned in this Convention.

United Kingdom of Great Britain and Northern Ireland
Upon signature:

       "The United Kingdom reserves the right to formulate, upon ratifying the Convention, any reservations or interpretative declarations which it might consider necessary."

United States of America 33
Upon signature :

Declaration:

       "The Government of the United States of America reserves the right to communicate, upon ratification, such reservations, interpretive understandings, or declarations as are deemed necessary."
Upon ratification :

Reservations:

       "I. The Senate's advice and consent is subject to the following reservations:
       (1) That the United States considers itself bound by the obligation under article 16 to prevent `cruel, inhuman or degrading treatment or punishment', only insofar as the term `cruel, inhuman or degrading treatment or punishment' means the cruel, unusual and inhumane treatment or punishment prohibited by the Fifth, Eighth, and/or Fourteenth Amendments to the Constitution of the United States.
       (2) That pursuant to article 30 (2) the United States declares that it does not consider itself bound by Article 30 (1), but reserves the right specifically to agree to follow this or any other procedure for arbitration in a particular case.
       II. The Senate's advice and consent is subject to the following understandings, which shall apply to the obligations of the United States under this Convention:
       (1) (a) That with reference to article 1, the United States understands that, in order to constitute torture, an act must be specifically intended to inflict severe physical or mental pain or suffering and that mental pain or suffering refers to prolonged mental harm caused by or resulting from (1) the intentional infliction or threatened infliction of severe physical pain or suffering; (2) the administration or application, or threatened administration or application, of mind altering substances or other procedures calculated to disrupt profoundly the senses or the personality; (3) the threat of imminent death; or (4) the threat that another person will imminently be subjected to death, severe physical pain or suffering, or the administration or application of mind altering substances or other procedures calculated to disrupt profoundly the senses or personality.
       (b) That the United States understands that the definition of torture in article 1 is intended to apply only to acts directed against persons in the offender's custody or physical control.
       (c) That with reference to article 1 of the Convention, the United States understands that `sanctions' includes judicially-imposed sanctions and other enforcement actions authorized by United States law or by judicial interpretation of such law. Nonetheless, the United States understands that a State Party could not through its domestic sanctions defeat the object and purpose of the Convention to prohibit torture.
       (d) That with reference to article 1 of the Convention, the United States understands that the term `acquiescence' requires that the public official, prior to the activity constituting torture, have awareness of such activity and thereafter breach his legal responsibility to intervene to prevent such activity.
       (e) That with reference to article 1 of the Convention, the Unites States understands that noncompliance with applicable legal procedural standards does not per se constitute torture.
       (2) That the United States understands the phrase, `where there are substantial grounds for believing that he would be in danger of being subjected to torture,' as used in article 3 of the Convention, to mean `if it is more likely than not that he would be tortured.'
       (3) That it is the understanding of the United States that article 14 requires a State Party to provide a private right of action for damages only for acts of torture committed in territory under the jurisdiction of that State Party.
       (4) That the United States understands that international law does not prohibit the death penalty, and does not consider this Convention to restrict or prohibit the United States from applying the death penalty consistent with the Fifth, Eighth and/or Fourteenth Amendments to the Constitution of the United States, including any constitutional period of confinement prior to the imposition of the death penalty.
       (5) That the United States understands that this Convention shall be implemented by the United States Government to the extent that it exercises legislative and judicial jurisdiction over the matters covered by the Convention and otherwise by the state and local governments. Accordingly, in implementing articles 10-14 and 16, the United States Government shall take measures appropriate to the Federal system to the end that the competent authorities of the constituent units of the United States of America may take appropriate measures for the fulfilment of the Convention.
       III. The Senate's advice and consent is subject to the following declarations:
       (1) That the United States declares that the provisions of articles 1 through 16 of the Convention are not self-executing.

Viet Nam
Declarations:

       “The Socialist Republic of Viet Nam declares, in accordance with article 28 paragraph 1, that it does not recognize the competence of the Committee provided for in article 20, and in accordance with article 30, paragraph 2, that it does not consider itself bound by article 30, paragraph 1.
       The Socialist Republic of Viet Nam does not consider the Convention as the direct legal basis for extradition in respect of the offences referred to in Article 4 of the Convention. Extradition shall be decided on the basis of extradition treaties to which Viet Nam is a party or the principle of reciprocity, and shall be in accordance with Vietnamese laws and regulations.”

Zambia 34
"""

# CIRIGHTS country names for matching/clean output
cirights = pd.read_excel("cirights_v3.xlsx")
valid_countries = set(cirights["country"].dropna().astype(str).str.strip().unique())

# Aliases for name alignment
candidate_aliases = {
    "USA": "United States",
    "UK": "United Kingdom",
    "Viet Nam": "Vietnam",
    "Republic of Korea": "South Korea",
    "Lao PDR": "Laos",
    "Russian Federation": "Russia",
    "Syrian Arab Republic": "Syria",
    "Türkiye": "Turkey",
    "Czech Republic": "Czechia",
}

aliases = {k: v for k, v in candidate_aliases.items() if v in valid_countries}

# Build search list
search_names = {c: c for c in valid_countries}
search_names.update(aliases)
search_items = sorted(search_names.items(), key=lambda x: len(x[0]), reverse=True)

# Split into rough country blocks
blocks = re.split(r'\n(?=[A-Z][A-Za-z\s\-\(\)\']+(?:\s\d+)?\n)', cat_text.strip())

rows = []

for block in blocks:
    block = block.strip()
    if not block:
        continue

    # Find country by matching the first line against CIRIGHTS names/aliases
    first_line = block.split("\n", 1)[0].strip()
    first_line_clean = re.sub(r"\s+\d+$", "", first_line).strip()

    country = None
    for search_name, canonical_name in search_items:
        if first_line_clean == search_name:
            country = canonical_name
            break

    if country is None:
        continue

    block_lower = block.lower()

    # Pure declarations only -> not counted as reservations
    has_reservation = bool(re.search(r'\breservations?\b', block_lower))
    has_decl_and_res = "declaration and reservation" in block_lower or "declarations and reservations" in block_lower
    has_only_declaration = ("declaration" in block_lower) and not has_reservation and not has_decl_and_res

    if has_only_declaration:
        cat_reservations = 0
    elif has_reservation or has_decl_and_res:
        # Count distinct article mentions inside the block
        article_matches = re.findall(r'article[s]?\s*(\d+)', block_lower)
        distinct_articles = sorted(set(article_matches))
        cat_reservations = len(distinct_articles) if distinct_articles else 1
    else:
        cat_reservations = 0

    rows.append((country, cat_reservations))

# Build dataframe and collapse duplicates conservatively
cat_res_df = pd.DataFrame(rows, columns=["country", "cat_reservations"])
cat_res_df = (
    cat_res_df.groupby("country", as_index=False)["cat_reservations"]
    .max()
    .sort_values("country")
    .reset_index(drop=True)
)

cat_res_df.head(20)

              country  cat_reservations
0         Afghanistan                 0
1             Austria                 0
2             Bahrain                 0
3             Belarus                 0
4            Botswana                 1
5            Bulgaria                 0
6               Chile                 1
7               China                 2
8                Cuba                 0
9      Czech Republic                 0
10           Dominica                 2
11            Ecuador                 1
12  Equatorial Guinea                 3
13            Eritrea                 3
14             France                 1
15            Germany                 1
16              Ghana                 0
17          Guatemala                 0
18      Guinea-Bissau                 0
19            Hungary                 0

In [89]:
cat_res_df.sort_values("cat_reservations", ascending=False).head(20)

                     country  cat_reservations
44  United States of America                 6
31                    Poland                 5
24                Mauritania                 3
21                    Israel                 3
13                   Eritrea                 3
12         Equatorial Guinea                 3
33                     Samoa                 3
20                 Indonesia                 2
35              South Africa                 2
28                      Oman                 2
10                  Dominica                 2
7                      China                 2
34              Saudi Arabia                 2
4                   Botswana                 1
38                  Thailand                 1
40                   Tunisia                 1
39                      Togo                 1
26                   Morocco                 1
22                    Kuwait                 1
25                    Monaco                 1

In [90]:
cat_df["country"] = cat_df["country"].replace({
    "United States of America": "United States",
    "Russian Federation": "Russia",
    "Czech Republic": "Czechia",
    "Viet Nam": "Vietnam"
})

In [92]:
cat_df = cat_year_df.merge(cat_res_df, on="country", how="left")
cat_df["cat_reservations"] = cat_df["cat_reservations"].fillna(0)

cat_df.tail()

                                       country  cat_year  cat_reservations
77                    United States of America    1994.0               6.0
78                                     Uruguay    1986.0               0.0
79                                   Venezuela    1991.0               0.0
80                                    Viet Nam    2015.0               0.0
81  Yugoslavia (Socialist Federal Republic of)    1991.0               0.0

## merge everything

In [93]:
cirights_df = cirights[[
    "country", "year",
    "Physical Integrity Rights Index",
    "Freedom of Speech",
    "Judicial Independence",
    "Women's Economic Rights"
]].copy()

cirights_df.columns = [
    "country", "year",
    "physical_integrity",
    "speech",
    "judicial_independence",
    "women_econ"
]

In [94]:
df = cirights_df.merge(cedaw_df, on=["country", "year"], how="left")
df = df.merge(iccpr_df, on="country", how="left")
df = df.merge(cat_df, on="country", how="left")

In [101]:
df.tail(10)

,country,year,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat_year,cat_reservations,cat
7923,South Sudan,2013,2.0,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,0
7924,South Sudan,2014,2.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0
7925,South Sudan,2015,1.0,0.0,1.0,1.0,1.0,0.0,NaN,NaN,NaN,0
7926,South Sudan,2016,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,0
7927,South Sudan,2017,0.0,0.0,NaN,0.0,1.0,0.0,NaN,NaN,NaN,0
7928,South Sudan,2018,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,0
7929,South Sudan,2019,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,0
7930,South Sudan,2020,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,0
7931,South Sudan,2021,1.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,0
7932,South Sudan,2022,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,0

In [103]:
df_2017 = df[df["year"] == 2017].copy()

# --- FINAL LOGIC STEP (2017 CROSS-SECTION) ---

# 1. Keep only 2017
df_2017 = df[df["year"] == 2017].copy()

# 2. Treaty membership
df_2017["cat"] = df_2017["cat_year"].notna().astype(int)
# (CEDAW already exists as "cedaw")

# 3. Clean reservations
df_2017["cat_reservations"] = df_2017["cat_reservations"].fillna(0) * df_2017["cat"]
df_2017["iccpr_reservations"] = df_2017["iccpr_reservations"].fillna(0)
df_2017["cedaw_reservations"] = df_2017["cedaw_reservations"].fillna(0) * df_2017["cedaw"]

# 4. Total reservations
df_2017["reservations_total"] = (
    df_2017["iccpr_reservations"] +
    df_2017["cedaw_reservations"] +
    df_2017["cat_reservations"]
)

# 5. Final clean dataset
df_2017 = df_2017[[
    "country",
    "physical_integrity",
    "speech",
    "judicial_independence",
    "women_econ",
    "cedaw",
    "cedaw_reservations",
    "iccpr_reservations",
    "cat",
    "cat_reservations",
    "reservations_total"
]].reset_index(drop=True)

df_2017.head()

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
0,Afghanistan,2.0,0.0,0.0,0.0,1.0,0.0,1.0,1,0.0,1.0
1,Albania,7.0,1.0,1.0,1.0,1.0,0.0,0.0,0,0.0,0.0
2,Algeria,6.0,1.0,1.0,2.0,1.0,4.0,1.0,1,0.0,5.0
3,Andorra,8.0,2.0,2.0,2.0,1.0,0.0,0.0,1,0.0,0.0
4,Angola,3.0,0.0,1.0,1.0,1.0,0.0,0.0,1,0.0,0.0

In [104]:
df_2017.sort_values("reservations_total", ascending=False).head(10)

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,0,0.0,18.0
12,Bahrain,3.0,0.0,1.0,0.0,1.0,5.0,5.0,0,0.0,10.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
109,Malta,8.0,1.0,2.0,1.0,1.0,4.0,4.0,0,0.0,8.0
9,Austria,8.0,2.0,2.0,3.0,1.0,0.0,8.0,1,0.0,8.0
125,New Zealand,8.0,2.0,2.0,3.0,1.0,2.0,4.0,1,1.0,7.0
175,Trinidad and Tobago,7.0,2.0,1.0,2.0,1.0,1.0,6.0,0,0.0,7.0
82,Israel,2.0,1.0,1.0,0.0,1.0,3.0,1.0,1,3.0,7.0
140,Qatar,8.0,0.0,0.0,2.0,1.0,7.0,0.0,0,0.0,7.0
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0

In [105]:
# --- INSPECTION ---

# 1. Basic structure
print("Shape:", df_2017.shape)
print("\nColumns:\n", df_2017.columns.tolist())

# 2. Missing values
print("\nMissing values:\n", df_2017.isna().sum())

# 3. Summary stats
print("\nSummary stats:\n")
display(df_2017.describe())

# 4. Check variation in key variables
print("\nReservations distribution:\n")
print(df_2017["reservations_total"].value_counts().sort_index())

# 5. Top reservation countries
print("\nTop countries by reservations:\n")
display(df_2017.sort_values("reservations_total", ascending=False).head(15))

# 6. Spot check important countries
check_countries = ["Denmark", "France", "India", "Saudi Arabia", "United States"]
print("\nSpot check:\n")
display(df_2017[df_2017["country"].isin(check_countries)])

# 7. Correlation matrix (nice quick sanity check)
print("\nCorrelation matrix:\n")
display(df_2017.corr(numeric_only=True))

Shape: (195, 11)

Columns:
 ['country', 'physical_integrity', 'speech', 'judicial_independence', 'women_econ', 'cedaw', 'cedaw_reservations', 'iccpr_reservations', 'cat', 'cat_reservations', 'reservations_total']

Missing values:
 country                   0
physical_integrity        0
speech                    3
judicial_independence    23
women_econ                2
cedaw                     1
cedaw_reservations        1
iccpr_reservations        0
cat                       0
cat_reservations          0
reservations_total        1
dtype: int64

Summary stats:

,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
count,195.000000,192.000000,172.000000,193.000000,194.000000,194.000000,195.000000,195.000000,195.000000,194.000000
mean,5.389744,0.838542,1.127907,1.227979,0.958763,0.680412,0.630769,0.364103,0.143590,1.458763
std,2.426634,0.758873,0.761601,0.889666,0.199353,1.429130,1.459797,0.482416,0.665728,2.428426
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8.000000,1.000000,2.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,2.000000
max,8.000000,2.000000,2.000000,3.000000,1.000000,9.000000,9.000000,1.000000,6.000000,18.000000

Reservations distribution:

reservations_total
0.0     107
1.0      30
2.0      13
3.0      12
4.0       9
5.0       9
6.0       5
7.0       4
8.0       3
10.0      1
18.0      1
Name: count, dtype: int64

Top countries by reservations:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,0,0.0,18.0
12,Bahrain,3.0,0.0,1.0,0.0,1.0,5.0,5.0,0,0.0,10.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
109,Malta,8.0,1.0,2.0,1.0,1.0,4.0,4.0,0,0.0,8.0
9,Austria,8.0,2.0,2.0,3.0,1.0,0.0,8.0,1,0.0,8.0
125,New Zealand,8.0,2.0,2.0,3.0,1.0,2.0,4.0,1,1.0,7.0
175,Trinidad and Tobago,7.0,2.0,1.0,2.0,1.0,1.0,6.0,0,0.0,7.0
82,Israel,2.0,1.0,1.0,0.0,1.0,3.0,1.0,1,3.0,7.0
140,Qatar,8.0,0.0,0.0,2.0,1.0,7.0,0.0,0,0.0,7.0
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
116,Monaco,8.0,1.0,2.0,2.0,1.0,4.0,2.0,0,0.0,6.0
184,United States of America,6.0,NaN,NaN,NaN,0.0,0.0,0.0,1,6.0,6.0
168,Syria,0.0,0.0,0.0,0.0,1.0,5.0,1.0,0,0.0,6.0
167,Switzerland,8.0,2.0,2.0,2.0,1.0,2.0,4.0,1,0.0,6.0
182,United Arab Emirates,4.0,0.0,NaN,0.0,1.0,5.0,0.0,0,0.0,5.0

Spot check:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
47,Denmark,8.0,2.0,2.0,3.0,1.0,0.0,3.0,1,0.0,3.0
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
150,Saudi Arabia,3.0,0.0,0.0,1.0,1.0,2.0,0.0,0,0.0,2.0

Correlation matrix:

,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
physical_integrity,1.000000,0.622524,0.715953,0.435835,0.021942,-0.072134,0.248917,0.124736,-0.015676,0.104525
speech,0.622524,1.000000,0.649283,0.414057,-0.003664,-0.113005,0.280267,0.174112,0.007337,0.103681
judicial_independence,0.715953,0.649283,1.000000,0.326984,0.032216,-0.037485,0.343306,0.092089,-0.080192,0.177305
women_econ,0.435835,0.414057,0.326984,1.000000,0.050114,0.003068,0.327300,0.206969,-0.034089,0.193183
cedaw,0.021942,-0.003664,0.032216,0.050114,1.000000,0.098995,0.090118,0.049933,-0.188704,0.060686
cedaw_reservations,-0.072134,-0.113005,-0.037485,0.003068,0.098995,1.000000,0.315520,-0.122434,0.005153,0.779983
iccpr_reservations,0.248917,0.280267,0.343306,0.327300,0.090118,0.315520,1.000000,0.199204,-0.030029,0.779686
cat,0.124736,0.174112,0.092089,0.206969,0.049933,-0.122434,0.199204,1.000000,0.285775,0.125591
cat_reservations,-0.015676,0.007337,-0.080192,-0.034089,-0.188704,0.005153,-0.030029,0.285775,1.000000,0.259457
reservations_total,0.104525,0.103681,0.177305,0.193183,0.060686,0.779983,0.779686,0.125591,0.259457,1.000000

In [106]:
# --- FIX COUNTRY NAME MISMATCHES ---

name_map = {
    "United States of America": "United States",
    "UK": "United Kingdom",
    "Russian Federation": "Russia",
    "Viet Nam": "Vietnam",
    "Syrian Arab Republic": "Syria",
    "Czech Republic": "Czechia",
    "Republic of Korea": "South Korea",
    "United Republic of Tanzania": "Tanzania"
}

df_2017["country"] = df_2017["country"].replace(name_map)

In [108]:
# --- FINAL CLEAN + CHECK + SAVE BLOCK ---

import pandas as pd

# 1. Fix country names
name_map = {
    "United States of America": "United States",
    "UK": "United Kingdom",
    "Russian Federation": "Russia",
    "Viet Nam": "Vietnam",
    "Syrian Arab Republic": "Syria",
    "Czech Republic": "Czechia",
    "Republic of Korea": "South Korea",
    "United Republic of Tanzania": "Tanzania"
}

df_2017["country"] = df_2017["country"].replace(name_map)

# 2. Quick sanity checks
print("Shape:", df_2017.shape)

print("\nMissing values:\n", df_2017.isna().sum())

print("\nTop countries by reservations:\n")
display(df_2017.sort_values("reservations_total", ascending=False).head(15))

print("\nSpot check:\n")
display(df_2017[df_2017["country"].isin([
    "United States", "United Kingdom", "France",
    "India", "Saudi Arabia", "Russia", "Vietnam"
])])

# 3. Check duplicates
duplicates = df_2017[df_2017.duplicated(subset=["country"], keep=False)]
print("\nDuplicates (should be empty):")
display(duplicates)

# 4. Optional: clean version (no NaNs)
df_clean = df_2017.dropna().copy()
print("\nOriginal shape:", df_2017.shape)
print("Clean shape:", df_clean.shape)

# 5. Save datasets
df_2017.to_csv("legal_dataset_2017.csv", index=False)
df_2017.to_excel("legal_dataset_2017.xlsx", index=False)

df_clean.to_csv("legal_dataset_2017_clean.csv", index=False)

print("\nSaved:")
print("- legal_dataset_2017.csv")
print("- legal_dataset_2017.xlsx")
print("- legal_dataset_2017_clean.csv")

Shape: (195, 11)

Missing values:
 country                   0
physical_integrity        0
speech                    3
judicial_independence    23
women_econ                2
cedaw                     1
cedaw_reservations        1
iccpr_reservations        0
cat                       0
cat_reservations          0
reservations_total        1
dtype: int64

Top countries by reservations:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,0,0.0,18.0
12,Bahrain,3.0,0.0,1.0,0.0,1.0,5.0,5.0,0,0.0,10.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
109,Malta,8.0,1.0,2.0,1.0,1.0,4.0,4.0,0,0.0,8.0
9,Austria,8.0,2.0,2.0,3.0,1.0,0.0,8.0,1,0.0,8.0
125,New Zealand,8.0,2.0,2.0,3.0,1.0,2.0,4.0,1,1.0,7.0
175,Trinidad and Tobago,7.0,2.0,1.0,2.0,1.0,1.0,6.0,0,0.0,7.0
82,Israel,2.0,1.0,1.0,0.0,1.0,3.0,1.0,1,3.0,7.0
140,Qatar,8.0,0.0,0.0,2.0,1.0,7.0,0.0,0,0.0,7.0
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
116,Monaco,8.0,1.0,2.0,2.0,1.0,4.0,2.0,0,0.0,6.0
184,United States,6.0,NaN,NaN,NaN,0.0,0.0,0.0,1,6.0,6.0
168,Syria,0.0,0.0,0.0,0.0,1.0,5.0,1.0,0,0.0,6.0
167,Switzerland,8.0,2.0,2.0,2.0,1.0,2.0,4.0,1,0.0,6.0
182,United Arab Emirates,4.0,0.0,NaN,0.0,1.0,5.0,0.0,0,0.0,5.0

Spot check:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
142,Russia,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0,0.0,1.0
150,Saudi Arabia,3.0,0.0,0.0,1.0,1.0,2.0,0.0,0,0.0,2.0
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,0,0.0,18.0
184,United States,6.0,NaN,NaN,NaN,0.0,0.0,0.0,1,6.0,6.0
189,Vietnam,4.0,0.0,NaN,1.0,1.0,1.0,0.0,0,0.0,1.0

Duplicates (should be empty):

Empty DataFrame
Columns: [country, physical_integrity, speech, judicial_independence, women_econ, cedaw, cedaw_reservations, iccpr_reservations, cat, cat_reservations, reservations_total]
Index: []

Original shape: (195, 11)
Clean shape: (171, 11)

Saved:
- legal_dataset_2017.csv
- legal_dataset_2017.xlsx
- legal_dataset_2017_clean.csv

In [109]:
# --- COUNTRY NAME DIAGNOSTIC + FIX BLOCK ---

import pandas as pd

# 1. Copy datasets so we don't overwrite originals by accident
cirights_check = cirights.copy()
iccpr_check = iccpr_df.copy()
cedaw_check = cedaw_df.copy()
cat_check = cat_df.copy()

# 2. Standardize whitespace
for d in [cirights_check, iccpr_check, cedaw_check, cat_check]:
    d["country"] = d["country"].astype(str).str.strip()

# 3. Add/expand shared rename map here
name_map = {
    "United States of America": "United States",
    "USA": "United States",
    "UK": "United Kingdom",
    "Russian Federation": "Russia",
    "Viet Nam": "Vietnam",
    "Syrian Arab Republic": "Syria",
    "Czech Republic": "Czechia",
    "Republic of Korea": "South Korea",
    "United Republic of Tanzania": "Tanzania",
    "Türkiye": "Turkey",
    "Lao PDR": "Laos",
}

# 4. Apply the same map to every treaty dataset and CIRIGHTS
for d in [cirights_check, iccpr_check, cedaw_check, cat_check]:
    d["country"] = d["country"].replace(name_map)

# 5. Build country sets
cirights_countries = set(cirights_check["country"].dropna().unique())
iccpr_countries = set(iccpr_check["country"].dropna().unique())
cedaw_countries = set(cedaw_check["country"].dropna().unique())
cat_countries = set(cat_check["country"].dropna().unique())

# 6. Show unmatched countries relative to CIRIGHTS
print("ICCPR not matching CIRIGHTS:")
print(sorted(iccpr_countries - cirights_countries))

print("\nCEDAW not matching CIRIGHTS:")
print(sorted(cedaw_countries - cirights_countries))

print("\nCAT not matching CIRIGHTS:")
print(sorted(cat_countries - cirights_countries))

print("\nCountries in CIRIGHTS missing from ICCPR:")
print(sorted(cirights_countries - iccpr_countries)[:50], "...")

print("\nCountries in CIRIGHTS missing from CEDAW:")
print(sorted(cirights_countries - cedaw_countries)[:50], "...")

print("\nCountries in CIRIGHTS missing from CAT:")
print(sorted(cirights_countries - cat_countries)[:50], "...")

# 7. Check a few key countries explicitly
check_names = [
    "United States", "United Kingdom", "Russia", "Vietnam",
    "Syria", "Czechia", "South Korea", "Tanzania"
]

print("\nKey-country presence check:")
for name in check_names:
    print(
        name,
        "| CIRIGHTS:", name in cirights_countries,
        "| ICCPR:", name in iccpr_countries,
        "| CEDAW:", name in cedaw_countries,
        "| CAT:", name in cat_countries
    )

# 8. If everything looks good, overwrite originals with cleaned names
cirights["country"] = cirights_check["country"]
iccpr_df["country"] = iccpr_check["country"]
cedaw_df["country"] = cedaw_check["country"]
cat_df["country"] = cat_check["country"]

ICCPR not matching CIRIGHTS:
[]

CEDAW not matching CIRIGHTS:
['nan']

CAT not matching CIRIGHTS:
['Byelorussian Soviet Socialist Republic', 'Federal Republic of Germany', 'Gambia', 'German Democratic Republic', "Lao People's Democratic Republic", 'Ukrainian Soviet Socialist Republic', 'Union of Soviet Socialist Republics', 'United Kingdom of Great Britain and Northern Ireland', 'Yugoslavia (Socialist Federal Republic of)']

Countries in CIRIGHTS missing from ICCPR:
['Albania', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Armenia', 'Azerbaijan', 'Belarus', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia Herzegovenia', 'Brazil', 'Brunei', 'Burkina Faso', 'Burma', 'Burma (Myanmar)', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Democratic Republic of', 'Congo, Republic of', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Czechoslovakia', 'Côte d’Ivoire', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'East Timor (Timor Leste)', 'East Timor (Timor-Leste)', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini'] ...

Countries in CIRIGHTS missing from CEDAW:
['Serbia'] ...

Countries in CIRIGHTS missing from CAT:
['Albania', 'Antigua and Barbuda', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bosnia Herzegovenia', 'Brunei', 'Burkina Faso', 'Burma', 'Burma (Myanmar)', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Central African Republic', 'Chad', 'Congo, Democratic Republic of', 'Congo, Republic of', "Cote d'Ivoire", 'Croatia', 'Czechia', 'Côte d’Ivoire', 'Djibouti', 'Dominica', 'East Timor', 'East Timor (Timor Leste)', 'East Timor (Timor-Leste)', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Gambia, The', 'Georgia', 'Germany', 'Grenada', 'Guatemala', 'Haiti', 'Honduras', 'India', 'Iran', 'Iraq'] ...

Key-country presence check:
United States | CIRIGHTS: True | ICCPR: False | CEDAW: True | CAT: True
United Kingdom | CIRIGHTS: True | ICCPR: True | CEDAW: True | CAT: False
Russia | CIRIGHTS: True | ICCPR: True | CEDAW: True | CAT: False
Vietnam | CIRIGHTS: True | ICCPR: True | CEDAW: True | CAT: True
Syria | CIRIGHTS: True | ICCPR: True | CEDAW: True | CAT: False
Czechia | CIRIGHTS: True | ICCPR: False | CEDAW: True | CAT: False
South Korea | CIRIGHTS: True | ICCPR: True | CEDAW: True | CAT: False
Tanzania | CIRIGHTS: True | ICCPR: False | CEDAW: True | CAT: False

In [110]:
# --- FINAL 2017 PATCH + REBUILD BLOCK ---

import pandas as pd

# 1. Fix obvious country-name mismatches in CAT / CEDAW / ICCPR
extra_name_map = {
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "Federal Republic of Germany": "Germany",
    "Lao People's Democratic Republic": "Laos",
    "Gambia": "Gambia, The",
    "Russian Federation": "Russia",
    "Viet Nam": "Vietnam",
    "Syrian Arab Republic": "Syria",
    "Czech Republic": "Czechia",
    "Republic of Korea": "South Korea",
    "United Republic of Tanzania": "Tanzania",
    "Türkiye": "Turkey"
}

for d in [iccpr_df, cedaw_df, cat_df]:
    d["country"] = d["country"].astype(str).str.strip().replace(extra_name_map)

# 2. Manually patch ICCPR United States if missing
if "United States" not in set(iccpr_df["country"]):
    iccpr_df = pd.concat([
        iccpr_df,
        pd.DataFrame([{"country": "United States", "iccpr_reservations": 6}])
    ], ignore_index=True)

# 3. Drop junk / historical CAT rows not relevant for 2017
drop_countries = [
    "Byelorussian Soviet Socialist Republic",
    "German Democratic Republic",
    "Ukrainian Soviet Socialist Republic",
    "Union of Soviet Socialist Republics",
    "Yugoslavia (Socialist Federal Republic of)"
]

cat_df = cat_df[~cat_df["country"].isin(drop_countries)].copy()

# 4. Rebuild merged dataset
cirights_df = cirights[[
    "country", "year",
    "Physical Integrity Rights Index",
    "Freedom of Speech",
    "Judicial Independence",
    "Women's Economic Rights"
]].copy()

cirights_df.columns = [
    "country", "year",
    "physical_integrity",
    "speech",
    "judicial_independence",
    "women_econ"
]

df = cirights_df.merge(cedaw_df, on=["country", "year"], how="left")
df = df.merge(iccpr_df, on="country", how="left")
df = df.merge(cat_df, on="country", how="left")

# 5. Keep only 2017
df_2017 = df[df["year"] == 2017].copy()

# 6. Treaty membership / reservation logic for 2017
df_2017["cat"] = df_2017["cat_year"].notna().astype(int)

df_2017["cedaw"] = df_2017["cedaw"].fillna(0)
df_2017["cedaw_reservations"] = df_2017["cedaw_reservations"].fillna(0) * df_2017["cedaw"]

df_2017["iccpr_reservations"] = df_2017["iccpr_reservations"].fillna(0)

df_2017["cat_reservations"] = df_2017["cat_reservations"].fillna(0) * df_2017["cat"]

df_2017["reservations_total"] = (
    df_2017["iccpr_reservations"] +
    df_2017["cedaw_reservations"] +
    df_2017["cat_reservations"]
)

# 7. Final columns
df_2017 = df_2017[[
    "country",
    "physical_integrity",
    "speech",
    "judicial_independence",
    "women_econ",
    "cedaw",
    "cedaw_reservations",
    "iccpr_reservations",
    "cat",
    "cat_reservations",
    "reservations_total"
]].reset_index(drop=True)

# 8. Quick checks
print("Shape:", df_2017.shape)

print("\nSpot check:")
display(df_2017[df_2017["country"].isin([
    "United States", "United Kingdom", "France",
    "India", "Saudi Arabia", "Russia", "Vietnam",
    "Germany", "Laos", "Gambia, The"
])])

print("\nTop reservations:")
display(df_2017.sort_values("reservations_total", ascending=False).head(15))

Shape: (195, 11)

Spot check:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
63,"Gambia, The",6.0,1.0,1.0,3.0,1.0,0.0,0.0,1,0.0,0.0
65,Germany,8.0,1.0,2.0,2.0,1.0,0.0,5.0,1,0.0,5.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
94,Laos,6.0,0.0,1.0,2.0,1.0,0.0,1.0,1,0.0,1.0
142,Russia,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0,0.0,1.0
150,Saudi Arabia,3.0,0.0,0.0,1.0,1.0,2.0,0.0,0,0.0,2.0
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,1,0.0,18.0
184,United States,6.0,NaN,NaN,NaN,0.0,0.0,6.0,1,6.0,12.0
189,Vietnam,4.0,0.0,NaN,1.0,1.0,1.0,0.0,1,0.0,1.0

Top reservations:

,country,physical_integrity,speech,judicial_independence,women_econ,cedaw,cedaw_reservations,iccpr_reservations,cat,cat_reservations,reservations_total
183,United Kingdom,8.0,2.0,2.0,3.0,1.0,9.0,9.0,1,0.0,18.0
184,United States,6.0,NaN,NaN,NaN,0.0,0.0,6.0,1,6.0,12.0
12,Bahrain,3.0,0.0,1.0,0.0,1.0,5.0,5.0,0,0.0,10.0
109,Malta,8.0,1.0,2.0,1.0,1.0,4.0,4.0,0,0.0,8.0
77,India,2.0,0.0,1.0,1.0,1.0,3.0,5.0,0,0.0,8.0
9,Austria,8.0,2.0,2.0,3.0,1.0,0.0,8.0,1,0.0,8.0
175,Trinidad and Tobago,7.0,2.0,1.0,2.0,1.0,1.0,6.0,0,0.0,7.0
82,Israel,2.0,1.0,1.0,0.0,1.0,3.0,1.0,1,3.0,7.0
125,New Zealand,8.0,2.0,2.0,3.0,1.0,2.0,4.0,1,1.0,7.0
140,Qatar,8.0,0.0,0.0,2.0,1.0,7.0,0.0,0,0.0,7.0
116,Monaco,8.0,1.0,2.0,2.0,1.0,4.0,2.0,0,0.0,6.0
168,Syria,0.0,0.0,0.0,0.0,1.0,5.0,1.0,0,0.0,6.0
167,Switzerland,8.0,2.0,2.0,2.0,1.0,2.0,4.0,1,0.0,6.0
61,France,7.0,1.0,2.0,3.0,1.0,2.0,3.0,1,1.0,6.0
65,Germany,8.0,1.0,2.0,2.0,1.0,0.0,5.0,1,0.0,5.0

In [111]:
# Check all US-like rows in the original CIRIGHTS file
cirights[
    cirights["country"].astype(str).str.contains("United States", case=False, na=False)
][[
    "country", "year",
    "Physical Integrity Rights Index",
    "Freedom of Speech",
    "Judicial Independence",
    "Women's Economic Rights"
]].sort_values(["country", "year"]).tail(20)

,country,year,Physical Integrity Rights Index,Freedom of Speech,Judicial Independence,Women's Economic Rights
7539,United States,2003,6.0,NaN,NaN,NaN
7540,United States,2004,4.0,NaN,NaN,NaN
7541,United States,2005,4.0,NaN,NaN,NaN
7542,United States,2006,4.0,NaN,NaN,NaN
7543,United States,2007,5.0,NaN,NaN,NaN
7544,United States,2008,6.0,NaN,NaN,NaN
7545,United States,2009,5.0,NaN,NaN,NaN
7546,United States,2010,6.0,NaN,NaN,NaN
7547,United States,2011,6.0,NaN,NaN,NaN
7548,United States,2012,6.0,NaN,NaN,NaN
7549,United States,2013,6.0,NaN,NaN,NaN
7550,United States,2014,6.0,NaN,NaN,NaN
7551,United States,2015,4.0,NaN,NaN,NaN
7552,United States,2016,3.0,NaN,NaN,NaN
7553,United States,2017,6.0,NaN,NaN,NaN
7554,United States,2018,4.0,NaN,NaN,NaN
7555,United States,2019,3.0,NaN,NaN,NaN
7556,United States,2020,2.0,NaN,NaN,NaN
7557,United States,2021,4.0,1.0,2.0,2.0
7558,United States,2022,2.0,2.0,2.0,2.0